### ISSUE TITLE
New connection taking ~10ms

### ISSUE THREAD

**Issue by nammehra** [openresty/lua-resty-redis#232] opened 2021-07-01 09:23 UTC
When connecting to AWS Elasticache redis cluster, new connection creation takes around ~10s but when a connection is used from the connection pool the connect call takes 0 ms. There are no errors in redis slow-log and openresty logs. Checked with AWS team , there seems to be no error from elasticache redis cluster side.

How can i check why new connection creation is taking so much time?
Also why there is no error in the logs even though set_timeouts for connection is set to 1sec.

Currently we are having 1 ngx worker process , 255 worker connections , and redis connection pool of 50.

Please can someone help me in understanding why this is happening, is there something which i am doing wrong.

**Comment by matth-c3** [comment] 2021-07-06 19:58
Hello @nammehra , 

Im wondering the same question, did you find something ?

Thanks

**Comment by nammehra** [comment] 2021-07-07 05:32
Hello @matth-c3 ,
Sorry I didn't find anything useful. Incase you find something , do post it here.

Thanks

**Comment by toredash** [comment] 2021-07-07 06:45
> Currently we are having 1 ngx worker process , 255 worker connections , and redis connection pool of 50.
> 

Shouldn't worker connection and pool size be equal? In this config, you would only be able to have 50 connections open to redis. Could the 10ms waiting time be related to nginx waiting for an available connection?

Is it 10 ms, or 10 seconds?

**Comment by nammehra** [comment] 2021-07-07 06:52
I tried with 255 connecttion pool size as well , but it didnt help.
And the time taken is 10seconds.

**Comment by toredash** [comment] 2021-07-07 08:09
> I tried with 255 connecttion pool size as well , but it didnt help.
> And the time taken is 10seconds.

That sounds like a DNS resolver timeout. Are you using the fqdn of elasticache? Could you try using the IP directly, and check what nginx is using for resolver_timeout?

**Comment by nammehra** [comment] 2021-07-07 08:13
I am using the primary/readers endpoint provided by aws elasticache. 
Also everytime its not taking this much time , its only for few request it takes more time.

**Comment by toredash** [comment] 2021-07-07 08:32
So you are using the fqdn. I would try to use the IP directly and see if you see the same issue. It's not recommended as the IP can change over time, but it would help since you could eliminate if this is a DNS issue or not.

It's hard to help when your not providing relevant and requested config options.

As it happens in-frequently I suspect DNS resolver issues, as established connections will be reused and will not be affected by DNS issue. Note that you could be hitting limits on the VPC DNS resolver at AWS, if your not using host/app level DNS caching it will resolve on every new redis connection which could exhaust your resource quota.

**Comment by nammehra** [comment] 2021-07-07 10:04
Ok, let me try with ipaddress and update the findings.

Thanks

**Comment by nammehra** [comment] 2021-07-07 12:09
> So you are using the fqdn. I would try to use the IP directly and see if you see the same issue. It's not recommended as the IP can change over time, but it would help since you could eliminate if this is a DNS issue or not.
> 
> It's hard to help when your not providing relevant and requested config options.
> 
> As it happens in-frequently I suspect DNS resolver issues, as established connections will be reused and will not be affected by DNS issue. Note that you could be hitting limits on the VPC DNS resolver at AWS, if your not using host/app level DNS caching it will resolve on every new redis connection which could exhaust your resource quota.

I tried with Ipaddress and seems to work. Thanks
I will check on how to enable DNS caching at host/app level.

**Comment by toredash** [comment] 2021-07-07 13:43
Please close the issue if the issue is resolved

**Closed** 2021-07-08 06:58 UTC
