### ISSUE TITLE
请问如何验证set_keepalive(reids连接池)生效

### ISSUE THREAD

**Issue by yanyumiao** [openresty/lua-resty-redis#123] opened 2017-06-23 09:14 UTC
读了下介绍  然后按照自己的想法验证了下redis连接池是否生效
1 nginx配置
location /lua {
    #lua_code_cache off;  
     default_type 'text/plain';
     content_by_lua_file /usr/local/nginx1.10.1/lua/access.lua;
}  

2 access.lua
redis = require "redis"
red = redis:new()
red:set_timeout(500) -- ms
ok, err = red:connect("127.0.0.1", 6379)
if not ok then
    ngx.say("failed to connect redis: ", err)
end
ngx.sleep(3) -- tcp status : ESTABLISHED
local ok, err = red:set_keepalive(10000, 10) -- tcp status : TIME_WAIT
if not ok then
    ngx.say("failed to set keepalive: ", err)
end

3 测试
访问这段代码时(curl 127.0.0.1/lua)，因为会有ngx.sleep(3)，
这期间通过netstat -anlp | grep 6379 能够看到有一个nginx进程和redis建立了连接(ESTABLISHED)

按照我的理解，因为线程池设置了10s的生存周期，上述逻辑运行完后，nginx进程和redis的连接应该继续保持ESTABLISHED，实际测试发现 ngx.sleep(3) 之后，nginx和redis的连接状态变成了TIME_WAIT

4 请问我这种验证连接池的办法是否正确，如果正确的话，上述会不会是一个bug？

**Comment by agentzh** [comment] 2017-06-23 17:56
Please, do not use Chinese here. This place is considered English only. If you
really want to use Chinese, please join and post to the openresty (Chinese)
mailing list instead. Please see https://openresty.org/en/community.html Thanks for
your cooperation.

Regarding your question, it seems that you are not loading the lua-resty-redis library in the correct way. The correct syntax is

```lua
local redis = local "resty.redis"
```

Maybe you misconfigured your `lua_package_path` directive (if you are using OpenResty, `resty.redis` should be visible in the default search paths by default).

I tried the following example based on your example and the connection pool works correctly on my side (I increased the max idle time from 10 sec to 100 sec to give enough time for the netstat command afterwards):

```nginx
location = /t {
    content_by_lua_block {
        local redis = require "resty.redis"
        local red = redis:new()
        red:set_timeout(500) -- ms
        ok, err = red:connect("127.0.0.1", 6379)
        if not ok then
        ngx.say("failed to connect redis: ", err)
        end
        -- ngx.sleep(3) -- tcp status : ESTABLISHED
        local ok, err = red:set_keepalive(100000, 10) -- tcp status : TIME_WAIT
        if not ok then
        ngx.say("failed to set keepalive: ", err)
        end
    }
}
```

After doing the `GET /t` request, I checked the connections like this:

```
$ netstat -nt|grep 6379
tcp        0      0 127.0.0.1:42542         127.0.0.1:6379          ESTABLISHED
tcp        0      0 127.0.0.1:6379          127.0.0.1:42542         ESTABLISHED
```

Enabling the `ngx.sleep()` call gives the same result.

Because I cannot reproduce it on my side, I'm closing this. If you still believe there is an issue in this library, please provide a minimal and self-contained example that we can reproduce the problem on our side. Thank you.

**Closed by agentzh** 2017-06-23 17:56 UTC

**Comment by agentzh** [comment] 2017-06-23 17:57
@yanyumiao BTW, to make the connection pool work properly, you must NOT turn off `lua_code_cache` (which is on by default). Otherwise the connection pool will be destroyed upon request termination.

**Comment by yanyumiao** [comment] 2017-06-26 03:42
Thank you very much for you answer.
My fault is that I set **lua_code_cache off**;
and I will translate this question to english later

**Comment by rupamkhaitan** [comment] 2017-12-22 02:55
I tried your sample code with /t location block with same keepalive setting
Our redis server is running on 10.X.X.1
and machine which is on 10.X.X.2 is having the lua location code makes a redis connetion on 10.X.X.1 IP & within 2 seconds we go to the redis machine box (we see FIN_ACK is sent by the box running the lua code)

netstat -nt | grep 6379

It goes into TIME_WAIT state

**Comment by rupamkhaitan** [comment] 2017-12-22 03:06
Here is the sample config file we tried with (exact same code) and on the redis-server which is idle and not doing any other process, it goes into TIME_WAIT after 2 secs, (we did packet capture as well and the box where lua code is running is sending FIN_ACK)

`worker_processes  1;
error_log logs/error.log;
events {
    worker_connections 1024;
}

http {
    server {
        listen 8080;
        location /test {
		lua_code_cache on;
   	 content_by_lua_block {
        	local redis = require "resty.redis"
    	    	local red = redis:new()
        	red:set_timeout(500000) -- ms
   	     	ok, err = red:connect("10.140.134.38", 6379)
       		if not ok then
        		ngx.say("failed to connect redis: ", err)
        	end
        	-- ngx.sleep(3) -- tcp status : ESTABLISHED
       		 local ok, err = red:set_keepalive(1000000, 10) -- tcp status : TIME_WAIT
        	if not ok then
                    ngx.log(ngx.ERR, "set keep alive error", err);
        		ngx.say("failed to set keepalive: ", err);
        	end
	    }
	}
    }
}`

**Comment by spacewander** [comment] 2017-12-22 03:20
@rupamkhaitan 
Could you enable the [debug log](http://nginx.org/en/docs/debugging_log.html) and paste it here to show what happened inside?

BTW, hijack other issue is a rude behavior, you should open a new issue instead.

**Comment by rupamkhaitan** [comment] 2017-12-22 03:43
Hi Spacewander,

I am so sorry I shouldnt have posted in this thread, really sorry

I enabled the debug logs by adding the statement (i dont see any issue)

Inside logs/error.log I see

2017/12/21 19:40:03 [notice] 19674#19674: using the "epoll" event method
2017/12/21 19:40:03 [notice] 19674#19674: openresty/1.13.6.1
2017/12/21 19:40:03 [notice] 19674#19674: OS: Linux 3.19.0-80-generic
2017/12/21 19:40:03 [notice] 19674#19674: getrlimit(RLIMIT_NOFILE): 1024:4096
2017/12/21 19:40:03 [notice] 19675#19675: start worker processes
2017/12/21 19:40:03 [notice] 19675#19675: start worker process 19676
2017/12/21 19:40:03 [notice] 19675#19675: start worker process 19677
2017/12/21 19:40:03 [notice] 19675#19675: start worker process 19678
2017/12/21 19:40:03 [notice] 19675#19675: start worker process 19680
2017/12/21 19:40:03 [notice] 19675#19675: start worker process 19681
2017/12/21 19:40:03 [notice] 19675#19675: start worker process 19682
2017/12/21 19:40:03 [notice] 19675#19675: start worker process 19683
2017/12/21 19:40:03 [notice] 19675#19675: start worker process 19684
2017/12/21 19:40:03 [notice] 19675#19675: start worker process 19685
2017/12/21 19:40:03 [notice] 19675#19675: start worker process 19686

inside logs/access.log I see

172.26.120.126 - - [21/Dec/2017:19:40:19 -0800] "GET /test HTTP/1.1" 200 5 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36"

**Comment by rupamkhaitan** [comment] 2017-12-22 22:13
created new issue here https://github.com/openresty/lua-resty-redis/issues/140
